# Generated by Django 4.1.7 on 2023-04-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="students_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("roll", models.CharField(max_length=255)),
                ("dept", models.CharField(max_length=255)),
                ("hostel", models.CharField(max_length=255)),
            ],
        ),
    ]
